# Generated by Django 5.1.5 on 2025-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_adddepartment_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddepartment',
            name='department_start_date',
        ),
        migrations.AddField(
            model_name='adddepartment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='adddepartment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
